### ISSUE TITLE
build: cylon rivanna recipie is failing

### ISSUE THREAD

**Issue by laszewsk** [cylondata/cylon#665] opened 2023-08-02 12:28 UTC
[3%] Compiling Cython CXX source for lib...
warning: pyarrow/lib.pxd:33:60: The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.
warning: pyarrow/includes/libarrow.pxd:1687:24: Rvalue-reference as function argument not supported
warning: pyarrow/includes/libarrow.pxd:1712:26: Rvalue-reference as function argument not supported
warning: pyarrow/includes/libarrow.pxd:1728:23: Rvalue-reference as function argument not supported
warning: pyarrow/includes/libarrow.pxd:1742:24: Rvalue-reference as function argument not supported
warning: pyarrow/includes/libarrow.pxd:2087:20: Rvalue-reference as function argument not supported
warning: pyarrow/error.pxi:82:60: The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.
warning: pyarrow/error.pxi:143:23: The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.
[  3%] Built target lib_pyx
[  7%] Building CXX object CMakeFiles/lib.dir/lib.cpp.o
/gpfs/gpfs0/project/bii_dsc_community/thf2bn/cylon/build/arrow/arrow/python/build/temp.linux-x86_64-3.7/lib.cpp: In function ‘PyObject* __pyx_pf_7pyarrow_3lib_15SparseCOOTensor_9dim_names_7__get___genexpr(PyObject*, std::vector<std::__cxx11::basic_string<char> >)’:
/gpfs/gpfs0/project/bii_dsc_community/thf2bn/cylon/build/arrow/arrow/python/build/temp.linux-x86_64-3.7/lib.cpp:162522:58: error: passing ‘const std::vector<std::__cxx11::basic_string<char> >’ as ‘this’ argument discards qualifiers [-fpermissive]
162522 |                   __pyx_cur_scope->__pyx_genexpr_arg_0 = __pyx_genexpr_arg_0;
       | ^~~~~~~~~~~~~~~~~~~
In file included from /sfs/applications/202307/software/standard/core/gcc/9.2.0/include/c++/9.2.0/vector:72,
                 from /gpfs/gpfs0/project/bii_dsc_community/thf2bn/cylon/build/arrow/arrow/python/build/temp.linux-x86_64-3.7/lib.cpp:1132:
/sfs/applications/202307/software/standard/core/gcc/9.2.0/include/c++/9.2.0/bits/vector.tcc:198:5: note:   in call to ‘std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(const std::vector<_Tp, _Alloc>&) [with _Tp = std::__cxx11::basic_string<char>; _Alloc = std::allocator<std::__cxx11::basic_string<char> >]’
  198 |     vector<_Tp, _Alloc>::
      |     ^~~~~~~~~~~~~~~~~~~
/gpfs/gpfs0/project/bii_dsc_community/thf2bn/cylon/build/arrow/arrow/python/build/temp.linux-x86_64-3.7/lib.cpp: In function ‘PyObject* __pyx_pf_7pyarrow_3lib_15SparseCSRMatrix_9dim_names_7__get___genexpr(PyObject*, std::vector<std::__cxx11::basic_string<char> >)’:
/gpfs/gpfs0/project/bii_dsc_community/thf2bn/cylon/build/arrow/arrow/python/build/temp.linux-x86_64-3.7/lib.cpp:166075:58: error: passing ‘const std::vector<std::__cxx11::basic_string<char> >’ as ‘this’ argument discards qualifiers [-fpermissive]
166075 |                   __pyx_cur_scope->__pyx_genexpr_arg_0 = __pyx_genexpr_arg_0;
       | ^~~~~~~~~~~~~~~~~~~
In file included from /sfs/applications/202307/software/standard/core/gcc/9.2.0/include/c++/9.2.0/vector:72,
                 from /gpfs/gpfs0/project/bii_dsc_community/thf2bn/cylon/build/arrow/arrow/python/build/temp.linux-x86_64-3.7/lib.cpp:1132:
/sfs/applications/202307/software/standard/core/gcc/9.2.0/include/c++/9.2.0/bits/vector.tcc:198:5: note:   in call to ‘std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(const std::vector<_Tp, _Alloc>&) [with _Tp = std::__cxx11::basic_string<char>; _Alloc = std::allocator<std::__cxx11::basic_string<char> >]’
  198 |     vector<_Tp, _Alloc>::
      |     ^~~~~~~~~~~~~~~~~~~
/gpfs/gpfs0/project/bii_dsc_community/thf2bn/cylon/build/arrow/arrow/python/build/temp.linux-x86_64-3.7/lib.cpp: In function ‘PyObject* __pyx_pf_7pyarrow_3lib_15SparseCSCMatrix_9dim_names_7__get___genexpr(PyObject*, std::vector<std::__cxx11::basic_string<char> >)’:
/gpfs/gpfs0/project/bii_dsc_community/thf2bn/cylon/build/arrow/arrow/python/build/temp.linux-x86_64-3.7/lib.cpp:169518:58: error: passing ‘const std::vector<std::__cxx11::basic_string<char> >’ as ‘this’ argument discards qualifiers [-fpermissive]
169518 |                   __pyx_cur_scope->__pyx_genexpr_arg_0 = __pyx_genexpr_arg_0;
       | ^~~~~~~~~~~~~~~~~~~
In file included from /sfs/applications/202307/software/standard/core/gcc/9.2.0/include/c++/9.2.0/vector:72,
                 from /gpfs/gpfs0/project/bii_dsc_community/thf2bn/cylon/build/arrow/arrow/python/build/temp.linux-x86_64-3.7/lib.cpp:1132:
/sfs/applications/202307/software/standard/core/gcc/9.2.0/include/c++/9.2.0/bits/vector.tcc:198:5: note:   in call to ‘std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(const std::vector<_Tp, _Alloc>&) [with _Tp = std::__cxx11::basic_string<char>; _Alloc = std::allocator<std::__cxx11::basic_string<char> >]’
  198 |     vector<_Tp, _Alloc>::
      |     ^~~~~~~~~~~~~~~~~~~
/gpfs/gpfs0/project/bii_dsc_community/thf2bn/cylon/build/arrow/arrow/python/build/temp.linux-x86_64-3.7/lib.cpp: In function ‘PyObject* __pyx_pf_7pyarrow_3lib_15SparseCSFTensor_9dim_names_7__get___genexpr(PyObject*, std::vector<std::__cxx11::basic_string<char> >)’:
/gpfs/gpfs0/project/bii_dsc_community/thf2bn/cylon/build/arrow/arrow/python/build/temp.linux-x86_64-3.7/lib.cpp:172824:58: error: passing ‘const std::vector<std::__cxx11::basic_string<char> >’ as ‘this’ argument discards qualifiers [-fpermissive]
172824 |                   __pyx_cur_scope->__pyx_genexpr_arg_0 = __pyx_genexpr_arg_0;
       | ^~~~~~~~~~~~~~~~~~~
In file included from /sfs/applications/202307/software/standard/core/gcc/9.2.0/include/c++/9.2.0/vector:72,
                 from /gpfs/gpfs0/project/bii_dsc_community/thf2bn/cylon/build/arrow/arrow/python/build/temp.linux-x86_64-3.7/lib.cpp:1132:
/sfs/applications/202307/software/standard/core/gcc/9.2.0/include/c++/9.2.0/bits/vector.tcc:198:5: note:   in call to ‘std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(const std::vector<_Tp, _Alloc>&) [with _Tp = std::__cxx11::basic_string<char>; _Alloc = std::allocator<std::__cxx11::basic_string<char> >]’
  198 |     vector<_Tp, _Alloc>::
      |     ^~~~~~~~~~~~~~~~~~~
gmake[2]: *** [CMakeFiles/lib.dir/lib.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/lib.dir/all] Error 2
gmake: *** [all] Error 2
error: command '/apps/software/standard/core/cmake/3.23.3/bin/cmake' failed with exit code 2
(cylon_rct) thf2bn@rivanna:/project/bii_dsc_community/thf2bn/cylon$

-- 
Gregor von Laszewski
[laszewski@gmail.com](mailto:laszewski@gmail.com)

**Comment by arupcsedu** [comment] 2023-08-02 14:05
This is the new issue due to changes on cython release. Are you using conda env build or python env build?

**Comment by laszewsk** [comment] 2023-08-02 14:39
This is the deployment we kicked off yesterday on rivanna.

**Comment by arupcsedu** [comment] 2023-08-02 22:20
The issue is fixed. Commit is on the way. This will fix the CI error as
well.

**Comment by arupcsedu** [comment] 2023-08-03 03:51
This issue is fixed in CI and Rivanna build as well.

Could anyone approve the PR?

**Comment by arupcsedu** [comment] 2023-08-03 14:13
I’ll approve it in a few minutes unless Niranda already has done so….
________________________________

**Comment by arupcsedu** [comment] 2023-08-03 14:21
Which PR is it?

From: Staylor, Mills Wellons (qad5gv) ***@***.***>
Date: Thursday, August 3, 2023 at 10:13 AM
To: Arup Sarker ***@***.***>, cylondata/cylon ***@***.***>, Gregor von Laszewski ***@***.***>
Cc: cylondata/cylon ***@***.***>, Assign ***@***.***>, Geoffrey Fox ***@***.***>
Subject: Re: [Request for approval of PR][cylondata/cylon] build: cylon rivanna recipie is failing (Issue #665)
I’ll approve it in a few minutes unless Niranda already has done so….
________________________________

**Comment by arupcsedu** [comment] 2023-08-03 14:23
@Staylor, Mills Wellons (qad5gv) ***@***.***> ,

https://github.com/cylondata/cylon/pull/661

**Comment by arupcsedu** [comment] 2023-08-03 14:37
The issue is fixed and merged. Please pull the latest change

**Closed by arupcsedu** 2023-08-03 14:37 UTC
Labels: bug, priority:high
